### ISSUE TITLE
Problem with soft

### ISSUE THREAD

**Issue by Saltan08** [andrey-karklins/dota2_mineweeper_bot#1]
Hi, i have this problem,
Error processing board, trying again...: Invalid board size detected: (12, 11)
Can u help me?

**Comment by romualdVII** [comment]
> Hi, i have this problem, Error processing board, trying again...: Invalid board size detected: (12, 11) Can u help me?

I can help you. I always play games on my QHD monitor, and i'd never suspect that monitor resolution can affect anything. I lowered the resolution to FullHD (fps doesnt matter) and this "program" finally begins do .. something. Further resolution lowering doesn't help. Obviously, this program counts pixels, but not processing image of mine field. This approach doesn't bring good results, but, eventually, can help to "autosolve" all five levels (I spend hour, but didn't reach even lvl 4 - too many "no solution found").
Excuse me for my english :)

**Comment by andrey-karklins** [comment]
Thanks for reply. This is true, bot works only for FullHD resolution: 1920x1080. As also it doesn’t solve all levels, as it has only simple cases coverage. It is intended to be used with human interaction, so when it is stuck, it is best to pause it, take screenshot and find “less obvious” moves, and then resume the bot. I have achieved a few times level 5 with the bot, but never reached 35k, as you need to have 2.5 minutes remaining on the clock.

**Comment by Saltan08** [comment]
Thanks for the answer. Changing the resolution really helped!
