### ISSUE TITLE
Missing image file?

### ISSUE THREAD

**Issue by Azingus** [andrey-karklins/dota2_mineweeper_bot#11]
Not sure what exactly the issue is, but i keep getting this error when launching from the .exe

```
[ WARN:0@5.847] global loadsave.cpp:241 cv::findDecoder imread_('images/dota2_logo.png'): can't open/read file: check file path/integrity
Error processing board, trying again...: OpenCV(4.10.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\templmatch.cpp:588: error: (-215:Assertion failed) corr.rows <= img.rows + templ.rows - 1 && corr.cols <= img.cols + templ.cols - 1 in function 'cv::crossCorr'
```

I used 1920x1080 resolution and I don't have HDR enabled.

**Comment by andrey-karklins** [comment]
Run exe in the same folder where "images" folder from this repo is

**Comment by Azingus** [comment]
I don't know where this path is to begin with. I found one "images" folder in "SteamLibrary\steamapps\common\dota 2 beta\game\core\tools" but there was no "dota2_logo.png" inside. I ran the .exe from the "tools" folder anyway since "images" was also in there, but it still gave me the same error.

**Comment by Azingus** [comment]
Why are you closing this so early without even waiting for feedback whether or not that solved it @andrey-karklins ?

Cause it didn't.
