### ISSUE TITLE
Need bit more specification on resolution/window type

### ISSUE THREAD

**Issue by fceek** [andrey-karklins/dota2_mineweeper_bot#12]
I assume it does not only requires `Dota 2 with FullHD resolution: 1920x1080` but need (1080p screen) + (1080p resolution) + (screen set to primary display) + (standalone fullscreen)?

Tried several combos, got different errors:

- 4K Screen + 1920x1080 Res + Borderless: 
Error processing board, trying again...: Invalid board size detected: unable to match to predefined sizes.

- 4K Screen + 1920x1080 Res + Standalone Fullscreen:
Error processing board, trying again...: No matching cell image found with sufficient accuracy.
Error processing board, trying again...: Unable to detect board boundaries.

- 1080p Screen + 1920x1080 Res + Not Primary display:
Error processing board, trying again...: Unable to detect board boundaries.

**Comment by andrey-karklins** [comment]
To my knowledge you need to set you display resolution to 1920x1080 in windows settings and then set dota 2 resolution to “native display fullscreen”. Then check that all image filters are disabled, such as HDR and Nvidia/AMD coloring settings. Then it should work, at least I ve got one guy who said it worked on 4k monitor like this.

**Comment by fceek** [comment]
Ahh so it's the OS level resolution settings, never thought that was a thing. Understood, thank you!
