### ISSUE TITLE
The flag placement is not accurate at all

### ISSUE THREAD

**Issue by stiggy87** [andrey-karklins/dota2_mineweeper_bot#13]
When running the script, it will place flags and sometimes the flags are not on bomb locations.

This causes problems where it thinks it is solved but it isn't.

**Comment by andrey-karklins** [comment]
Didn’t notice such behaviour what is your display resolution?

**Comment by stiggy87** [comment]
1920x1080, but I have 3 monitors connected. When running the script, it was putting flags on positions that are not really bombs, so I had to go in manually and fix the locations so I can complete the level.

**Comment by andrey-karklins** [comment]
Are you sure that you have no color filters enabled, such as HDR or Nvidia/AMD color enhancements? It sounds like cell recognition fails. You can also have a look at the output in the terminal, what is the most common debug message there?

**Comment by stiggy87** [comment]
I have an AMD GPU, and I have not turned on any HDR. Attached is the "debug_board_detection.png".

As you can see it found everything, but on the last row, there are three mine flags which is incorrect. The center flag should not be there. 

![debug_board_detection](https://github.com/user-attachments/assets/70c3ead8-95e1-4e4b-b532-ebc8a761a634)

**Comment by stiggy87** [comment]
Here's another example:

![image](https://github.com/user-attachments/assets/a195e846-2f9c-463e-987d-9fb358b1957d)

**Comment by andrey-karklins** [comment]
This error can be happening only if cell images are close, but not exactly the same, so miss detection  happens. The only reasons I know of are: dota resultion / monitor resolution are not set to 1920 x 1080, or you are using something in AMD that changes the picture on your monitor. It worked for most of the people without miss detection of a single tile, if that happens so often to you, there must be something different in your setup.

**Comment by stiggy87** [comment]
The only thing I have enabled is the anti-lag, but that shouldn't affect anything like this.

I'll keep playing with it.
