### ISSUE TITLE
Unable to solve error 500

### ISSUE THREAD

**Issue by stiggy87** [andrey-karklins/dota2_mineweeper_bot#15]
When getting this image:

![image](https://github.com/user-attachments/assets/d4148026-82ea-4c70-99f2-bb4605e3cbe1)

I get the error 500 message saying it can't solve this. I believe the power-ups could be causing problems.

Here's another one:

![debug_board_detection](https://github.com/user-attachments/assets/7c7b2872-b69f-4bae-8415-13e4ae3a035b)

**Comment by andrey-karklins** [comment]
Duplicate
