### ISSUE TITLE
Occasional error 

### ISSUE THREAD

**Issue by FyreWhale** [andrey-karklins/dota2_mineweeper_bot#18]
When running the script, there are times where the script is able to run but after awhile it will always run into this issue. My monitor does not support HDR and I am not running any colour filter, I think.... My monitor resolution is also 1080 with 240Hz not sure if it affects it.

This is the error the will keep popping up in the console.
"No matching cell image found with sufficient accuracy."

![debug_board_detection](https://github.com/user-attachments/assets/b1c9918b-2f5d-448a-8ff5-eb322b61725d)
(Debug board)

![last_board](https://github.com/user-attachments/assets/7a88cde1-73c4-440d-bca2-4f02198a2191)
(Last Board)

**Comment by mwafi1998** [comment]
The Time Rune has changed by a bit, the clock hand is slightly thinner now. I sent a pull request that fixes this.

**Comment by andrey-karklins** [comment]
Merged fix
