### ISSUE TITLE
Error processing board

### ISSUE THREAD

**Issue by xmkos** [andrey-karklins/dota2_mineweeper_bot#3]
1920x1080 16:9 fullscreen windowed, or fullscreen, nor windowed gives
Error processing board, trying again...: Invalid board size detected: (9, 8)
Error processing board, trying again...: Invalid board size detected: (11, -6)

**Comment by andrey-karklins** [comment]
Unfortunately, that is the case now for screens that are not 1920x1080. I will look forward to rewriting the board detection logic later.

**Comment by andrey-karklins** [comment]
Try changing resolution in game
