### ISSUE TITLE
Any chance to get this to work with an ultrawide?

### ISSUE THREAD

**Issue by gtirsmiley** [andrey-karklins/dota2_mineweeper_bot#5]
Tried setting the required resolution but it just won't work properly.

Any suggestions?

**Comment by andrey-karklins** [comment]
Could you set the resolution in dota to 1920x1080, run the bot and have a look at debug image that is generated in the same folder as executable. Is it locating the board?

**Comment by gtirsmiley** [comment]
It does locate the board, it even does a few moves but it does it incorrectly. It clicks on bombs and fails. 
I think the few times I tried, it always clicked on the top left corner as the first move.

I have 27 files in the "images" folder

**Comment by Protomax-epk** [comment]
Also don't work with 1440p displays as it seems
tried:
native 1440p
dota at FHD 60hz bordereless and fullscreen
System size set at FHD + dota at FHD borderless

**Comment by andrey-karklins** [comment]
> It does locate the board, it even does a few moves but it does it incorrectly. It clicks on bombs and fails. I think the few times I tried, it always clicked on the top left corner as the first move.

This is correct behaviour. You should do first move yourself. Afterwards it should not be clicking on bombs :)

**Comment by andrey-karklins** [comment]
Unfortunately soft will not support ultrawide, unless someone does a pull request to change that.

**Comment by Fermander** [comment]
I tried changing windows resolution, in-game resolution, on a 21:9 monitor, no dice no matter what I tried.
