### ISSUE TITLE
ModuleNotFoundError: No module named 'cv2'

### ISSUE THREAD

**Issue by formidabilus** [andrey-karklins/dota2_mineweeper_bot#7]
Hello, I tried to install it from source code, but when I run it, gives this error: 

`❯ sudo python main.py
`
`Traceback (most recent call last):
  File "/dota2_mineweeper_bot/main.py", line 2, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'`

Any ideas? 
Thanks!

**Comment by andrey-karklins** [comment]
pip install -r requirements.txt

**Comment by formidabilus** [comment]
I already did that, I have the requirements installed, but it doesn't import.
